name: hello-world

values:
  application:
    name: PipeForge
  greeting: "Hello ${values.application.name}"

pipeline:
  - name: Hello
    env:
      GREETING: "${values.greeting}"
    script: python -c 'import os; print(os.environ["GREETING"])'

  - name: Working directory
    script: python -c 'from pathlib import Path; print("Running in", Path.cwd().name)'
